config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "/institutions/search", to: "institutions#search"
  resources :institutions
  get "students/search", to: "students#search"
  resources :students
  resources :enrollments
  resources :invoices

  # API JSON namespace
  namespace :api do
    namespace :v1 do
      resources :institutions, defaults: { format: :json }
      resources :students, defaults: { format: :json }
      resources :enrollments, defaults: { format: :json }
      resources :invoices, defaults: { format: :json }
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :enrollments

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :cnpj, presence: true,
                   uniqueness: { message: "Deve ser único para cada instituição" },
                   format: { with: /\A\d+\z/, message: "CNPJ deve conter apenas números" },
                   length: { is: 14 }
  validates :institution_type, presence: true, inclusion: { in: %w[universidade escola creche] }
  validates :status, presence: true, inclusion: { in: %w[enabled disabled] }
  validate :immutable_fields_after_creation, on: :update

  def immutable_fields_after_creation
    if cnpj_changed?
      errors.add(:cpf, "não pode ser alterado após a criação")
    end
  end
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }
  def index
    @institutions = Institution.all

    if params[:id].present?
      @institutions = @institutions.where("id LIKE ?", "%#{params[:id]}%")
    end

    if params[:name].present?
      @institutions = @institutions.where("LOWER(name) LIKE ?", "%#{params[:name].downcase}%")
    end

    if params[:cnpj].present?
      @institutions = @institutions.where("cnpj LIKE ?", "%#{params[:cnpj]}%")
    end

    if params[:institution_type].present?
      @institutions = @institutions.where(institution_type: params[:institution_type])
    end

    if params[:status].present? && params[:status] == "disabled"
      @institutions = @institutions.where(status: params[:status])
    elsif params[:status].present? && params[:status] == "enabled" || !params[:status].present?
      @institutions = @institutions.where(status: "enabled")
    else
      @institutions
    end

    respond_to do |format|
      format.html
      format.json { render json: @institutions }
    end
  end


  def show
    @institution = Institution.find(params[:id])
    
    respond_to do |format|
      format.html
      format.json { render json: @institution }
    end
  end

  def new
    @institution = Institution.new
  end

  def create
    @institution = Institution.new(institution_params.merge(status: "enabled"))
    if @institution.save
      respond_to do |format|
        format.html { redirect_to @institution, notice: "Instituição criada com sucesso!" }
        format.json { render json: @institution, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @institution.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @institution = Institution.find(params[:id])
  end

  def update
    @institution = Institution.find(params[:id])
    if @institution.update(institution_params)
      respond_to do |format|
        format.html { redirect_to @institution, notice: "Instituição atualizada com sucesso!" }
        format.json { render json: @institution }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @institution.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @institution = Institution.find(params[:id])
    if @institution.update(status: "disabled")
      respond_to do |format|
        format.html { redirect_to @institution, notice: "Instituição atualizada com sucesso!" }
        format.json { render json: { message: "Instituição desativado com sucesso." }, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @institution.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def search
    query = params[:q].to_s.downcase
    institutions = Institution.where("lower(name) LIKE ?", "%#{query}%").limit(20).select(:id, :name)
    render json: institutions
  end

  private

  def institution_params
    params.require(:institution).permit(:name, :cnpj, :institution_type)
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_institution_form.html.erb
<%= form_with(model: @institution, local: true) do |form| %>
  <div class="profile">
    <div class="profile-right">
      <ul>
        <li>
          <strong><%= form.label :name %></strong> 
          <%= form.text_field :name %>
        </li>
        <li>
          <strong><%= form.label :cnpj %></strong>
          <%= form.text_field :cnpj, maxlength: 14, pattern: '\d{14}', title: "CNPJ deve conter exatamente 14 números" %>
        </li>
        <li>
          <strong><%= form.label :institution_type %></strong>
          <%= form.select :institution_type, [["Universidade", "universidade"], ["Escola", "escola"], ["Creche", "creche"]] %>
        </li>
        <li>
          <%= form.submit %>
        </li>  
      </ul>
    </div>
  </div>

  <% if @institution.errors.any? %>
      <div id="error_explanation" style="background: #fdd; border: 1px solid red; padding: 10px; margin-bottom: 20px;">
          <h2><%= pluralize(@institution.errors.count, "erro") %> impediram o salvamento:</h2>
          <ul>
          <% @institution.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
          </ul>
      </div>
  <% end %>
<% end %>

app/views/institutions/edit.html.erb
<section>
    <h1>
        <%= link_to institution_path(@institution) do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Editar Instituição
    </h1>
    
    <%= render "institution_form" %>
</section>

app/views/institutions/index.html.erb
<section class="index">
    <div class="profile">
        <div class="profile-top">
        <%= form_with url: institutions_path, method: :get, local: true,html: { class: "form-busca" } do |form| %>
            <div>
                <%= form.label :id, "ID:" %>
                <%= form.text_field :id, placeholder: "Digite o id" %>
            </div>
            <div>
                <%= form.label :name, "Nome:" %>
                <%= form.text_field :name, placeholder: "Digite o nome" %>
            </div>
            <div>
                <%= form.label :cnpj, "CNPJ:" %>
                <%= form.text_field :cnpj, placeholder: "Digite o CNPJ" %>
            </div>
            <div>
                <%= form.label :institution_type, "Tipo:" %>
                <%= form.select :institution_type, options_for_select(["universidade", "escola", "creche"], params[:institution_type]), include_blank: "Todos" %>
            </div>
            <div>
                <%= form.label :status, "Status:"%>
                <%= form.select :status, options_for_select(["enabled", "disabled","todos"], params[:gender])%>
            </div>
            <%= form.submit "Buscar" %>

        <% end %>
        </div>

        <div class="profile-bottom">
            <table width="100%">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>CNPJ</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th colspan="3">Options</th>
                    </tr>
                    <% @institutions.each do |institution| %>
                    <tr>
                        <td><%= link_to institution.id, institution_path(institution) %></td>
                        <td><%= link_to institution.name, institution_path(institution) %></td>
                        <td><%= institution.cnpj %></td>
                        <td><%= institution.institution_type.humanize %></td>
                        <td><%= institution.status.capitalize %>
                        <td><%= link_to "View", institution_path(institution), class:"btn" %></td>
                        <td><%= link_to "Edit", edit_institution_path(institution), class:"btn" %></td>
                        <td><%= link_to "Delete", institution_path(institution), 
                                class: "btn-danger", 
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } %></td>                    
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</section>

app/views/institutions/new.html.erb
<section>
    
    <h1>
        <%= link_to institutions_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Nova Instituição
    </h1>

    <%= render "institution_form" %>
</section>

app/views/institutions/show.html.erb
<section>
    <h1>
        <%= link_to institutions_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Instituição
    </h1>

    <% if Institution.any? %>
    <div class="profile">
    <div class="profile-left <%= @institution.status == 'disabled' ? 'disabled-status' : '' %>">
        <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="Institution Icon" />
        <h2><%= @institution.name %></h2>
        <p><%= @institution.institution_type.capitalize %></p>
        <p><%= @institution.cnpj %></p>

        <div class="profile-buttons">
        <%= link_to "Editar", edit_institution_path(@institution), class: "btn edit" %>
        <%= link_to "Excluir", institution_path(@institution),
                    method: :delete,
                    data: { turbo_confirm: "Tem certeza que deseja excluir?" },
                    class: "btn delete" %>
        </div>
    </div>

    <div class="profile-right <%= @institution.status == 'disabled' ? 'disabled-status' : '' %>">
        <h3>Detalhes</h3>
        <ul>
        <li><strong>Id:</strong> <%= @institution.id%></li>
        <li><strong>Nome:</strong> <%= @institution.name %></li>
        <li><strong>CNPJ:</strong> <%= @institution.cnpj %></li>
        <li><strong>Tipo:</strong> <%= @institution.institution_type.capitalize %></li>
        <li><strong>Criada em:</strong> <%= l @institution.created_at.to_date %></li>
        <li><strong>Uptade em:</strong> <%= l @institution.updated_at.to_date %></li>
        <li><strong>Status:</strong> <%= @institution.status.capitalize %>
        </ul>
    </div>
    </div>
    <% end %>
</section>