config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "/institutions/search", to: "institutions#search"
  resources :institutions
  get "students/search", to: "students#search"
  resources :students
  resources :enrollments
  resources :invoices

  # API JSON namespace
  namespace :api do
    namespace :v1 do
      resources :institutions, defaults: { format: :json }
      resources :students, defaults: { format: :json }
      resources :enrollments, defaults: { format: :json }
      resources :invoices, defaults: { format: :json }
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :enrollment

  validates :invoice_price, presence: true
  validates :invoice_due_date, presence: true
  validates :status, presence: true, inclusion: { in: %w[open late paid disabled] }

  validate :immutable_fields_after_creation, on: :update

  def immutable_fields_after_creation
    if invoice_price_changed?
      errors.add(:invoice_price, "não pode ser alterado após a criação")
    end
    if invoice_due_date_changed?
      errors.add(:invoice_due_date, "não pode ser alterado após a criação")
    end
    if enrollment_id_changed?
      errors.add(:enrollment_id_changed, "não pode ser alterado após a criação")
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }

  def index
    @invoices = Invoice.all

    if params[:id].present?
      @invoices = @invoices.where("id LIKE ?", "%#{params[:id]}%")
    end

    if params[:invoice_price].present?
      @invoices = @invoices.where("invoice_price LIKE ?", "%#{params[:invoice_price]}%")
    end

    if params[:invoice_due_date].present?
      @invoices = @invoices.where("invoice_due_date LIKE ?", "%#{params[:invoice_due_date]}%")
    end

    if params[:status].present?
      @invoices = @invoices.where(status: params[:status])
    end

    respond_to do |format|
      format.html
      format.json { render json: @invoices }
    end
  end


  def show
    @invoice = Invoice.find(params[:id])
    @enrollment = @invoice.enrollment
    @parcel_number = @enrollment.invoices.order(:invoice_due_date).pluck(:id).index(@invoice.id) + 1
    @total_parcels = @enrollment.number_of_installments

    respond_to do |format|
      format.html
      format.json do
        render json: {
          invoice: @invoice,
          enrollment: @enrollment,
          parcel_number: @parcel_number,
          total_parcels: @total_parcels
        }
      end
    end
  end

  def update
    @invoice = Invoice.find(params[:id])
    if @invoice.update(invoice_params)
      respond_to do |format|
        format.html { redirect_to @invoice, notice: "Fatura atualizada com sucesso!" }
        format.json { render json: @invoice }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @invoice.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @invoice = Invoice.find(params[:id])
    if @invoice.update(status: "disabled")
      respond_to do |format|
        format.html { redirect_to @invoice, notice: "Fatura desabilitada com sucesso!" }
        format.json { render json: { message: "Invoice desativado com sucesso." }, status: :ok }
      end 
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @invoice.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  def invoice_params
    params.require(:invoice).permit(:invoice_price, :invoice_due_date, :status, :enrollment_id)
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/create.html.erb
<h1>Invoices#create</h1>
<p>Find me in app/views/invoices/create.html.erb</p>

app/views/invoices/destroy.html.erb
<h1>Invoices#destroy</h1>
<p>Find me in app/views/invoices/destroy.html.erb</p>

app/views/invoices/index.html.erb
<section class="index">
    <div class="profile">
        <div class="profile-top">
        <%= form_with url: invoices_path, method: :get, local: true,html: { class: "form-busca" } do |form| %>
            <div>
                <%= form.label :id, "ID:" %>
                <%= form.text_field :id, placeholder: "Digite o id" %>
            </div>
            <div>
                <%= form.label :invoice_price, "Valor:" %>
                <%= form.text_field :invoice_price, placeholder: "Valor da parcela" %>
            </div>
            <div>
                <%= form.label :invoice_due_date, "Data de Vencimento:" %>
                <%= form.date_field :invoice_due_date %>
            </div>
            <div>
                <%= form.label :status, "Status:" %>
                <%= form.select :status, options_for_select(["open", "late", "paid", "disabled"], params[:status]), include_blank: "Todos" %>
            </div>
            <%= form.submit "Buscar" %>

        <% end %>
        </div>

        <div class="profile-bottom">
            <table width="100%">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>ID Matrícula</th>
                        <th>Valor Parcela</th>
                        <th>Data de Vencimento</th>
                        <th>Status</th>
                        <th colspan="2">Options</th>
                    </tr>
                    <% @invoices.each do |invoice| %>
                    <tr>
                        <td><%= link_to invoice.id, invoice_path(invoice) %></td>
                        <td><%= link_to invoice.enrollment_id, enrollment_path(invoice.enrollment_id) %></td>
                        <td><%= invoice.invoice_price %></td>
                        <td><%= invoice.invoice_due_date %></td>
                        <td><%= invoice.status.humanize %></td>
                        <td><%= link_to "View", invoice_path(invoice), class:"btn" %></td>
                        <td><%= link_to "Delete", invoice_path(invoice), 
                                class: "btn-danger", 
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } %></td>                    
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</section>

app/views/invoices/show.html.erb
<section>
    <h1>
        <%= link_to invoices_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Invoices
    </h1>

    <% if Invoice.any? %>
    <div class="profile">
    <div class="profile-left <%= @invoice.status == 'disabled' ? 'disabled-status' : '' %>">
        <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="Institution Icon" />
        <h2><%= @invoice.enrollment.student.name %></h2>
        <p><%=  @invoice.enrollment.institution.name %></p>
        <p>Parcela: <%= @parcel_number %> / <%= @total_parcels %></p>

        <div class="profile-buttons">
        <%= link_to "Excluir", invoice_path(@invoice),
                    method: :delete,
                    data: { turbo_confirm: "Tem certeza que deseja excluir?" },
                    class: "btn delete" %>
        </div>
    </div>

    <div class="profile-right <%= @invoice.status == 'disabled' ? 'disabled-status' : '' %>">
        <h3>Detalhes</h3>
        <ul>
        <li><strong>Id:</strong> <%= @invoice.id%></li>
        <li><strong>Valor:</strong>R$ <%= @invoice.invoice_price %></li>
        <li><strong>Data de vencimento:</strong> <%= @invoice.invoice_due_date %></li>
        <li><strong>Enrollment:</strong> <%= @invoice.enrollment_id %></li>
        <li><strong>Criada em:</strong> <%= l @invoice.created_at.to_date %></li>
        <li><strong>Uptade em:</strong> <%= l @invoice.updated_at.to_date %></li>
        <li><Strong>Status:</strong><%= @invoice.status.capitalize %></li>
        </ul>
    </div>
    </div>
    <% end %>
</section>