config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "/institutions/search", to: "institutions#search"
  resources :institutions
  get "students/search", to: "students#search"
  resources :students
  resources :enrollments
  resources :invoices

  # API JSON namespace
  namespace :api do
    namespace :v1 do
      resources :institutions, defaults: { format: :json }
      resources :students, defaults: { format: :json }
      resources :enrollments, defaults: { format: :json }
      resources :invoices, defaults: { format: :json }
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :institution
  belongs_to :student
  has_many :invoices, dependent: :destroy

  validates :full_price,  presence: true,
                          numericality: { greater_than: 0 }
  validates :number_of_installments, presence: true,
                                  numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :due_day, presence: true,
                       numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 31 }
  validates :course_name, presence: true
  validates :student, presence: true
  validates :institution, presence: true
  validates :status, presence: true, inclusion: { in: %w[enabled disabled] }
  validate :institution_student_must_be_active

  after_create :generate_invoices

  private

  def institution_student_must_be_active
    if institution.status == "disabled"
      errors.add("Instituição está desativada e não pode aceitar novas matrículas.")
    end
    if student.status == "disabled"
      errors.add("Aluno está desativado e não pode aceitar novas matrículas.")
    end
  end

  def generate_invoices
    self.number_of_installments.times do |i|
      invoices.create!(
        invoice_price: calculate_installment_price,
        invoice_due_date: calculate_due_date(i),
        status: "open"
      )
    end
  end

  def calculate_installment_price
    return 0 if self.number_of_installments <= 0
    (self.full_price/self.number_of_installments).round(2)
  end

  def calculate_due_date(month_offset)
    if self.due_day >= Date.today.day
      today = Date.today >> month_offset
      due_date = verify_date(today)
    else
      today = Date.today >> month_offset+1
      due_date = verify_date(today)
    end
    due_date
  end

  def verify_date(day)
    if Date.valid_date?(day.year, day.month, self.due_day)
      due_date = Date.new(day.year, day.month, self.due_day)
    else
      due_date = Date.new(day.year, day.month, -1)
    end
    due_date
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: -> { request.format.json? }

  def index
    @enrollments = Enrollment.all

    if params[:id].present?
      @enrollments = @enrollments.where("id LIKE ?", "%#{params[:id]}%")
    end

    if params[:student_id].present?
      @enrollments = @enrollments.where("student_id LIKE ?", "%#{params[:student_id]}%")
    end

    if params[:institution_id].present?
      @enrollments = @enrollments.where("institution_id LIKE ?", "%#{params[:institution_id]}%")
    end

    if params[:course_name].present?
      @enrollments = @enrollments.where("LOWER(course_name) LIKE ?", "%#{params[:course_name].downcase}")
    end

    if params[:status].present? && params[:status] == "disabled"
      @enrollments = @enrollments.where(status: params[:status])
    elsif params[:status].present? && params[:status] == "enabled" || !params[:status].present?
      @enrollments = @enrollments.where(status: "enabled")
    else
      @enrollments
    end

    respond_to do |format|
      format.html
      format.json { render json: @enrollments }
    end
  end

  def show
    @enrollment = Enrollment.find(params[:id])
    @invoices = @enrollment.invoices.order(:invoice_due_date)

    respond_to do |format|
      format.html
      format.json { render json: { enrollment: @enrollment, invoices: @invoices } }
    end    
  end

  def new
    @enrollment = Enrollment.new
  end

  def create
    @enrollment = Enrollment.new(enrollment_params)
    if @enrollment.save
      respond_to do |format|
        format.html { redirect_to @enrollment, notice: "Matrícula criada com sucesso!" }
        format.json { render json: @enrollment, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: { errors: @enrollment.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @enrollment = Enrollment.find(params[:id])
  end

  def update
    @enrollment = Enrollment.find(params[:id])
    if @enrollment.update(enrollment_params)
      respond_to do |format|
        format.html { redirect_to @enrollment, notice: "Matrícula atualizada com sucesso!" }
        format.json { render json: @enrollment }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @enrollment.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @enrollment = Enrollment.find(params[:id])
    if @enrollment.update(status: "disabled")
      @enrollment.invoices.where(status: "open").update_all(status: "disabled")
      respond_to do |format|
        format.html { redirect_to @enrollment, notice: "Matrícula desativada com sucesso!" }
        format.json { render json: { message: "Matrícula desativado com sucesso." }, status: :ok }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: { errors: @enrollment.errors.full_messages }, status: :unprocessable_entity }
      end
    end
  end

  private

  def enrollment_params
    params.require(:enrollment).permit(:full_price, :number_of_installments, :due_day, :course_name, :institution_id, :student_id)
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment_form.html.erb
<%= form_with(model: @enrollment, local: true) do |form| %>
  <div class="profile">
    <div class="profile-right">
      <ul>
        <li data-controller="autocomplete" style="position: relative;">
            <strong><%= form.label :student_name, "Estudante" %></strong>
            <input type="text" data-autocomplete-target="input" data-action="input->autocomplete#search" autocomplete="off" />
            <div data-autocomplete-target="results" class="autocomplete-results"></div>

            <%= form.hidden_field :student_id %>
        </li>
        <li data-controller="autocomplete" style="position: relative;">
            <strong><%= form.label :institution_name, "Instituição" %></strong>
            <input type="text" data-autocomplete-target="input" data-autocomplete-type="institutions" data-action="input->autocomplete#search" autocomplete="off" />
            <div data-autocomplete-target="results" class="autocomplete-results"></div>
            <%= form.hidden_field :institution_id %>
        </li>
        <li>
          <strong><%= form.label :course_name %></strong> 
          <%= form.text_field :course_name %>
        </li>
        <li>
          <strong><%= form.label :full_price %></strong>
          <%= form.number_field :full_price, step: 0.01, min: 0, placeholder: "Ex: 1499.99" %>
        </li>
        <li>
          <strong><%= form.label :due_day %></strong>
          <%= form.number_field :due_day, in: 1..31 %>
        </li>
        <li>
          <strong><%= form.label :number_of_installments %></strong>
          <%= form.number_field :number_of_installments, min: 1 %>
        </li>
        <li>
          <%= form.submit %>
        </li>  
      </ul>
    </div>
  </div>

  <% if @enrollment.errors.any? %>
      <div id="error_explanation" style="background: #fdd; border: 1px solid red; padding: 10px; margin-bottom: 20px;">
          <h2><%= pluralize(@enrollment.errors.count, "erro") %> impediram o salvamento:</h2>
          <ul>
          <% @enrollment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
          </ul>
      </div>
  <% end %>
<% end %>

app/views/enrollments/edit.html.erb
<section>
    <h1>
        <%= link_to enrollments_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Editar Matrícula
    </h1>

    <%= render "enrollment_form" %>
</section>

app/views/enrollments/index.html.erb
<section class="index">
    <div class="profile">
        <div class="profile-top">
        <%= form_with url: enrollments_path, method: :get, local: true,html: { class: "form-busca" } do |form| %>
            <div>
                <%= form.label :id, "ID:" %>
                <%= form.text_field :id, placeholder: "Digite o id" %>
            </div>
            <div>
                <%= form.label :student_id, "Id do estudante:" %>
                <%= form.text_field :student_id, placeholder: "Id do estudante" %>
            </div>
            <div>
                <%= form.label :institution_id, "Id da Instituição:" %>
                <%= form.text_field :institution_id, placeholder: "Id da Instituição" %>
            </div>
            <div>
                <%= form.label :course_name, "Nome do curso"%>
                <%= form.text_field :course_name, placeholder: "Nome do Curso" %>
            </div>
            <div>
                <%= form.label :status, "Status:" %>
                <%= form.select :status, options_for_select(["enabled", "disabled", "todos"], params[:status]) %>
            </div>
            <%= form.submit "Buscar" %>

        <% end %>
        </div>

        <div class="profile-bottom">
            <table width="100%">
                <tbody>
                    <tr>
                        <th>ID</th>
                        <th>ID Estudante</th>
                        <th>ID Instituição</th>
                        <th>Nome do Curso</th>
                        <th>Preço</th>
                        <th># Parcelas</th>
                        <th>Dia vencimento</th>
                        <th>Status</th>
                        <th colspan="3">Options</th>
                    </tr>
                    <% @enrollments.each do |enrollment| %>
                    <tr>
                        <td><%= link_to enrollment.id, enrollment_path(enrollment) %></td>
                        <td><%= link_to enrollment.student_id, student_path(enrollment.student_id) %></td>
                        <td><%= link_to enrollment.institution_id, institution_path(enrollment.institution_id) %></td>
                        <td><%= enrollment.course_name %></td>
                        <td><%= enrollment.full_price %></td>
                        <td><%= enrollment.number_of_installments %>
                        <td><%= enrollment.due_day %></td>
                        <td><%= enrollment.status.capitalize %></td>
                        <td><%= link_to "View", enrollment_path(enrollment), class:"btn" %></td>
                        <td><%= link_to "Edit", edit_enrollment_path(enrollment), class:"btn" %></td>
                        <td><%= link_to "Delete", enrollment_path(enrollment), 
                                class: "btn-danger", 
                                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" } %></td>                    
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</section>

app/views/enrollments/new.html.erb
<section>
    <h1>
        <%= link_to enrollments_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Nova Matrícula
    </h1>

    <%= render "enrollment_form" %>
</section>

app/views/enrollments/show.html.erb
<section>
    <h1>
        <%= link_to enrollments_path do%>
            <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        Enrollment
    </h1>

    <% if Enrollment.any? %>
    <div class="profile">
        <div class="profile-left <%= @enrollment.status == 'disabled' ? 'disabled-status' : '' %>">
            <img src="https://cdn-icons-png.flaticon.com/512/3135/3135715.png" alt="Institution Icon" />
            <h2><%= @enrollment.student.name %></h2>
            <p><%= @enrollment.institution.name %></p>
            <p><%= @enrollment.course_name %></p>

            <div class="profile-buttons">
            <%= link_to "Editar", edit_enrollment_path(@enrollment), class: "btn edit" %>
            <%= link_to "Excluir", enrollment_path(@enrollment),
                        method: :delete,
                        data: { turbo_confirm: "Tem certeza que deseja excluir?" },
                        class: "btn delete" %>
            </div>
        </div>

        <div class="profile-right <%= @enrollment.status == 'disabled' ? 'disabled-status' : '' %>">
            <h3>Detalhes</h3>
            <ul>
                <li><strong>Id:</strong> <%= @enrollment.id%></li>
                <li><strong>Id do Estudante:</strong> <%= @enrollment.student_id %></li>
                <li><strong>Id da Instituição:</strong> <%= @enrollment.institution_id %></li>
                <li><strong>Nome do curso:</strong> <%= @enrollment.course_name %></li>
                <li><strong>Preço:</strong> <%= @enrollment.full_price %></li>
                <li><strong>Dia de vencimento:</strong> <%= @enrollment.due_day %></li>
                <li><strong>Número de parcelas:</strong> <%= @enrollment.number_of_installments %></li>
                <li><strong>Criada em:</strong> <%= l @enrollment.created_at.to_date %></li>
                <li><strong>Uptade em:</strong> <%= l @enrollment.updated_at.to_date %></li>
                <li><Strong>Status:</strong> <%= @enrollment.status.capitalize %>
            </ul>
        </div>

        <div class="profile-right <%= @enrollment.status == 'disabled' ? 'disabled-status' : '' %>">
            <h3>Invoices </h3>
            <table width="100%">
                <thead>
                    <tr>
                    <th>#</th>
                    <th>Valor</th>
                    <th>Vencimento</th>
                    <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    <% @invoices.each_with_index do |invoice, index| %>
                    <tr>
                        <td><%= index + 1 %></td>
                        <td><%= number_to_currency(invoice.invoice_price) %></td>
                        <td><%= invoice.invoice_due_date.strftime("%d/%m/%Y") %></td>
                        <td><%= invoice.status.capitalize %></td>
                    </tr>
                    <% end %>
                </tbody>
                </table>
        </div>
    </div>
    <% end %>
</section>