config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get "/institutions/search", to: "institutions#search"
  resources :institutions
  get "students/search", to: "students#search"
  resources :students
  resources :enrollments
  resources :invoices

  # API JSON namespace
  namespace :api do
    namespace :v1 do
      resources :institutions, defaults: { format: :json }
      resources :students, defaults: { format: :json }
      resources :enrollments, defaults: { format: :json }
      resources :invoices, defaults: { format: :json }
    end
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Bilinho" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    
    <script src="https://kit.fontawesome.com/4386879e19.js" crossorigin="anonymous"></script>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body>
  <header>
    <div class=logo>
      <%= link_to root_path do%>
        <i class="fa-solid fa-money-bill-1-wave"></i>
        Bilinho
     <% end %>
    </div>
    <nav>
      <% if controller_name == "institutions" %>  
      <ul>
        <li>
          <%= link_to new_institution_path do %>
            <i class="fa-solid fa-plus"></i> New Institution
          <% end %>
        </li>
      <ul>
      <% end %>
      <% if controller_name == "students" %>  
      <ul>
        <li>
          <%= link_to new_student_path do %>
            <i class="fa-solid fa-plus"></i> New Student
          <% end %>
        </li>
      <ul>
      <% end %>
      <% if controller_name == "enrollments" %>  
      <ul>
        <li>
          <%= link_to new_enrollment_path do %>
            <i class="fa-solid fa-plus"></i> New Enrollment
          <% end %>
        </li>
      <ul>
      <% end %>
    </nav>
  </header>
  <div class="wrapper">
    <div class="sidebar">
      <ul>
        <li>
          <%= link_to institutions_path, class: ("ativo" if controller_name == "institutions") do %>
            <i class="fa-solid fa-building-columns"></i> Institutions
          <% end %>
        </li>
        <li>
          <%= link_to students_path, class: ("ativo" if controller_name == "students") do %>
            <i class="fa-solid fa-user-graduate"></i> Students
          <% end %>
        </li>  
        <li>
          <%= link_to enrollments_path, class: ("ativo" if controller_name == "enrollments") do %>
            <i class="fa-solid fa-clipboard-check"></i> Enrollments
          <% end %>
        </li>
        <li>
          <%= link_to invoices_path, class: ("ativo" if controller_name == "invoices") do %>
            <i class="fa-solid fa-file-invoice-dollar"></i> Invoices
          <% end %>
        </li> 
      </ul>
      <footer>
        <ul>
          <li><a href="https://github.com/Bpelossi/Bilinho/blob/main/README.md"><i class="fa-brands fa-readme"></i>Read Me</a></li>
          <li><a href="https://www.linkedin.com/in/bruno-pelossi-71b690155"><i class="fa-brands fa-linkedin"></i>  Linkedin</a></li>
          <li><a href="https://github.com/Bpelossi"><i class="fa-brands fa-github"></i>  Github</a></li>
        </ul>
      </footer>
    </div>

    <main>
      <%= yield %>
    </main>
  </div>

</body>